name: Test deployment
defaults:
  run:
    shell: bash
    working-directory: ./documentation

on:
  pull_request:
    branches:
      - master

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Node.js version from .tool-versions
        id: node-version
        run: echo "NODE_VERSION=$(cat .tool-versions | egrep nodejs | awk '{print $2}' | xargs)" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm
          cache-dependency-path: ./documentation/package-lock.json

      - name: Install dependencies
        run: npm ci
      - name: Test build website
        run: npm run build