name: Test deployment
defaults:
  run:
    shell: bash
    working-directory: ./documentation

on:
  pull_request:
    branches:
      - master

jobs:
  test-docs-gen:
    name: Test Docs Generation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Cache asdf
        uses: actions/cache@v4
        with:
          path: |
            ~/.asdf
          key: ${{ runner.os }}-asdf-${{ hashFiles('.tool-versions') }}
          restore-keys: |
            ${{ runner.os }}-asdf-
      - uses: asdf-vm/actions/install@v4
      - run: task docs
